local GED = BaptismalPreloader.GenerateEntityDataset

return {
	Rumpling		= GED("Rumpling"),
	Skinling	= GED("Skinling"),
	Scabling	= GED("Scabling"),
	Scorchling	= GED("Scorchling"),
	Mortling	= GED("Mortling"),
	TaintedRumpling	= GED("Tainted Rumpling"),
	GildedRumpling	= GED("Gilded Rumpling"),
	FractureRM	= GED("​Fracture"),
	Necromancer	= GED("Necromancer"),
	Swapper = GED("Swapper"),
	SwapperGehenna = GED("Swapper (Gehenna)"),
	Barfy = GED("Barfy"),
	Screamer = GED("Screamer"),
	Cell = GED("Cell"),
	FusedCells = GED("Fused Cells"),
	Tissue = GED("Tissue"),
	GraveRobber = GED("Grave Robber"),
	SplashyLongLegs = GED("Splashy Long Legs"),
	StickyLongLegs = GED("Sticky Long Legs"),
	FireGrimace = GED("Fire Grimace"),
	Bloodworm = GED("Bloodworm"),
	VesselRM = GED("Vessel (RM)"),
	SplitRageCreep = GED("​Split Rage Creep"),
	RagCreep = GED("​Rag Creep"),
	VesselAntibirth = GED("​Vessel (Antibirth)"),
	Strifer = GED("​Strifer"),
}